//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;results&quot;:[{&quot;Name&quot;:&quot;Stokes Inc&quot;,&quot;UserName&quot;:&quot;mbernardot0&quot;,&quot;Password&quot;:&quot;MyJwFznFG&quot;,&quot;CountryCode&quot;:9},
        ///{&quot;Name&quot;:&quot;Schmitt and Sons&quot;,&quot;UserName&quot;:&quot;msposito1&quot;,&quot;Password&quot;:&quot;NMntajC&quot;,&quot;CountryCode&quot;:11},
        ///{&quot;Name&quot;:&quot;Mertz Inc&quot;,&quot;UserName&quot;:&quot;nlowne2&quot;,&quot;Password&quot;:&quot;DKL1ya6PwOXa&quot;,&quot;CountryCode&quot;:9},
        ///{&quot;Name&quot;:&quot;Jakubowski Inc&quot;,&quot;UserName&quot;:&quot;tpopley3&quot;,&quot;Password&quot;:&quot;dHAXhSyWUiIP&quot;,&quot;CountryCode&quot;:12},
        ///{&quot;Name&quot;:&quot;Olson, Greenfelder and Cartwright&quot;,&quot;UserName&quot;:&quot;rdelbergue4&quot;,&quot;Password&quot;:&quot;uSR7xxoS&quot;,&quot;CountryCode&quot;:12},
        ///{&quot;Name&quot;:&quot;Mosciski Inc&quot;,&quot;UserName&quot;:&quot;a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string airlinesJson {
            get {
                return ResourceManager.GetString("airlinesJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;results&quot;:[{&quot;FirstName&quot;:&quot;Buiron&quot;,&quot;LastName&quot;:&quot;Lambotin&quot;,&quot;UserName&quot;:&quot;blambotin0&quot;,&quot;Email&quot;:&quot;ifgw@bfhr.com&quot;,&quot;Password&quot;:&quot;jgqSML&quot;,&quot;Address&quot;:&quot;00249 Delladonna Trail&quot;,&quot;PhoneNo&quot;:&quot;222-192-2325&quot;,&quot;CreditCardNo&quot;:&quot;4936592390822146551&quot;},{&quot;FirstName&quot;:&quot;Stacie&quot;,&quot;LastName&quot;:&quot;Bortol&quot;,&quot;UserName&quot;:&quot;sbortol1&quot;,&quot;Email&quot;:&quot;ifgw@bfhr.com&quot;,&quot;Password&quot;:&quot;iWOKq38T&quot;,&quot;Address&quot;:&quot;2989 Anniversary Center&quot;,&quot;PhoneNo&quot;:&quot;662-310-0117&quot;,&quot;CreditCardNo&quot;:&quot;564182132317574669&quot;},{&quot;FirstName&quot;:&quot;Bobbi&quot;,&quot;LastName&quot;:&quot;Singh&quot;,&quot;UserName&quot;:&quot;bsingh2&quot;,&quot;Email&quot;:&quot;ifgw@bfhr.co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string customersJson {
            get {
                return ResourceManager.GetString("customersJson", resourceCulture);
            }
        }
    }
}
